---
settings:
  name: Azure Blob storage
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentación de almacenamiento de blobs de Azure
    url: "/index.html"
  - title: Notas de la versión
    url: "/whats-new.html"
  - title: Empezar
    entries:
    - title: Ver sus cuentas de almacenamiento de blobs de Azure
      url: "/task-view-azure-blob-storage.html"
  - title: Administrar cuentas de almacenamiento de blobs de Azure
    entries:
    - title: Agregar nuevas cuentas de almacenamiento
      url: "/task-add-blob-storage.html"
    - title: Cambiar la configuración de las cuentas de almacenamiento
      url: "/task-change-blob-storage-settings.html"
    - title: Utilice los servicios de datos de NetApp con Azure Blob Storage
      url: "/task-blob-enable-data-services.html"
  - title: Conocimiento y apoyo
    entries:
    - title: Regístrese para recibir asistencia
      url: "/task-support-registration.html"
    - title: Obtener ayuda
      url: "/task-get-help.html"
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: Storage Management
  repo: storage-management-family
