---
sidebar: sidebar 
permalink: task-blob-enable-data-services.html 
keywords: blob storage, blob working environment, azure blob storage accounts, azure blob working environment, system 
summary: Después de descubrir cuentas de almacenamiento de blobs de Azure en la NetApp Console, puede usar los servicios de datos de NetApp para realizar copias de seguridad, organizar en niveles y sincronizar datos. 
---
= Utilice los servicios de datos de NetApp con Azure Blob Storage
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Después de descubrir cuentas de almacenamiento de blobs de Azure en la NetApp Console, puede usar los servicios de datos de NetApp para realizar copias de seguridad, organizar en niveles y sincronizar datos.

* Utilice * NetApp Backup and Recovery* para realizar copias de seguridad de los datos de sus sistemas ONTAP locales y Cloud Volumes ONTAP en el almacenamiento de blobs de Azure.
+
Para comenzar, navegue a la página Sistemas.  Arrastre y suelte un sistema ONTAP local o Cloud Volumes ONTAP en su sistema Azure Blob Storage.

+
https://docs.netapp.com/us-en/data-services-backup-recovery/concept-ontap-backup-to-cloud.html["Obtenga más información sobre cómo realizar copias de seguridad de los datos de ONTAP en Azure Blob Storage"^] .

* Utilice * NetApp Cloud Tiering* para organizar en niveles los datos inactivos desde los clústeres ONTAP locales al almacenamiento de blobs de Azure.
+
Para comenzar, navegue a la página Sistemas.  Arrastre y suelte un sistema ONTAP local en su sistema Azure Blob Storage.

+
https://docs.netapp.com/us-en/data-services-cloud-tiering/task-tiering-onprem-azure.html["Obtenga más información sobre cómo organizar en niveles los datos de ONTAP en el almacenamiento de blobs de Azure"^] .

* Utilice * NetApp Copy and Sync* para sincronizar datos hacia o desde cuentas de almacenamiento de Azure Blob.
+
Para comenzar, navegue a la página Sistemas.  Arrastre y suelte el sistema de origen en el sistema de destino.  Su sistema de almacenamiento de blobs de Azure puede ser el origen o el destino.

+
También puede seleccionar su sistema Azure Blob Storage y luego *Copiar y sincronizar* desde el panel Servicios para sincronizar datos hacia o desde cuentas de Azure Blob Storage.

+
https://docs.netapp.com/us-en/data-services-copy-sync/concept-cloud-sync.html["Obtenga más información sobre Copiar y sincronizar"^] .


