---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, limitations, known issues, enhancements, fixes' 
summary: Descubra las novedades de Azure Blob Storage en la NetApp Console. 
---
= Novedades de Azure Blob Storage en la NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Descubra las novedades de Azure Blob Storage en la NetApp Console.



== 6 de octubre de 2025



=== BlueXP ahora es NetApp Console

BlueXP ha sido renombrado y rediseñado para reflejar mejor su función en la gestión de su infraestructura de datos.

La NetApp Console proporciona una gestión centralizada de servicios de almacenamiento y datos en entornos locales y en la nube a nivel empresarial, brindando información en tiempo real, flujos de trabajo más rápidos y una administración simplificada.

Para obtener más detalles sobre lo que ha cambiado, consulte la https://docs.netapp.com/us-en/console-relnotes/index.html["Notas de la versión de la NetApp Console"] .



== 5 de junio de 2023



=== Capacidad de agregar nuevas cuentas de almacenamiento desde BlueXP

Ha tenido la capacidad de ver Azure Blob Storage en BlueXP Canvas durante bastante tiempo.  Ahora puede agregar nuevas cuentas de almacenamiento y cambiar las propiedades de las cuentas de almacenamiento existentes directamente desde BlueXP. link:https://docs.netapp.com/us-en/storage-management-blob-storage/["Aprenda a agregar nuevas cuentas de almacenamiento de blobs de Azure"^] .
